# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirestackAndroid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirestackAndroid

  target 'FirestackAndroid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirestackAndroidTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FirestackAndroid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirestackAndroid-tvOS

  target 'FirestackAndroid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end
